services:
    nextjs:
        image: 'devops.apps.inspiritvision.com:8443/test:1.0.0'
        # build: .
        container_name: issp
        ports:
            - '3000:3000'
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - ~/.aws:/root/.aws:ro
            - ./config.yml:/app/config.yml:ro
            - ./crontab.txt:/app/crontab.txt

E2E_API_KEY=9e6e4078-7118-4a32-8621-c8835a3ef54e
E2E_AUTH_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGSjg2R2NGM2pUYk5MT2NvNE52WmtVQ0lVbWZZQ3FvcXRPUWVNZmJoTmxFIn0.eyJleHAiOjE4MjAyOTg3MzAsImlhdCI6MTc4ODc2MjczMCwianRpIjoiMGQ2YTc4MWItMzMwMC00ZTE5LThhMzgtMDMyMzA3ZWVmMWEyIiwiaXNzIjoiaHR0cDovL2dhdGV3YXkuZTJlbmV0d29ya3MuY29tL2F1dGgvcmVhbG1zL2FwaW1hbiIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJjODQ3MDU3MS1kNzNkLTRmZmMtYTFjOS02Njc3ZmVmOWFhYmYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhcGltYW51aSIsInNlc3Npb25fc3RhdGUiOiIxYzFlN2ZhYi02ZjUwLTRiMmQtODQzNC01OTJkMmQ2NWYwMGEiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImFwaXVzZXIiLCJkZWZhdWx0LXJvbGVzLWFwaW1hbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsInNpZCI6IjFjMWU3ZmFiLTZmNTAtNGIyZC04NDM0LTU5MmQyZDY1ZjAwYSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaXNfcGFydG5lcl9yb2xlIjpmYWxzZSwibmFtZSI6IkRocnV2IERhdmUiLCJwcmltYXJ5X2VtYWlsIjoic3VuaWwuc2FvQGluc3Bpcml0dmlzaW9uLmNvbSIsImlzX3ByaW1hcnlfY29udGFjdCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImRocnV2LmRhdmVAaW5zcGlyaXR2aXNpb24uY29tIiwiZ2l2ZW5fbmFtZSI6IkRocnV2IiwiZmFtaWx5X25hbWUiOiJEYXZlIiwiZW1haWwiOiJkaHJ1di5kYXZlQGluc3Bpcml0dmlzaW9uLmNvbSIsImlzX2luZGlhYWlfdXNlciI6ZmFsc2V9.Tq3KKOlIK4d2SxqKNrsvxL7VNmuF_cbrpULlLkSBr1NyZg5T1CIBW2RMvkt4sAi-_4jp8P91L7Yw8_w-0k8Y8S6K-evQenRGIsQIBcEJLiADKEF4Uk5tZ8vkWig7JTkqatvIpRKgyAWPJyDCTBIlrJYhNg1a0fsuv4tgDHkHcRA