profiles:
  infra:
    provider: aws
    regions:
      - ap-south-1
      - us-east-1
  product:
    provider: aws
    regions:
      - ap-south-1
  e2e-prod:
    provider: e2e
    projectId: "12345"
    regions:
      - Delhi
      - Mumbai