[supervisord]
nodaemon=true
user=root

[program:restore-crontab]
command=crontab /app/crontab.txt
priority=1
autostart=true
autorestart=false
startsecs=0

[program:cron]
command=crond -f
priority=2
autostart=true
autorestart=true

[program:node-app]
command=node server.js
directory=/app
priority=3
autostart=true
autorestart=true
