/* eslint-disable @typescript-eslint/no-explicit-any */
'use server'

import { getConfig } from '@/lib/config'
import { sendSlackNotification } from '@/lib/notifications'
import { findTag } from '@/lib/utils'
import {
	DescribeInstancesCommand,
	EC2Client,
	Instance,
} from '@aws-sdk/client-ec2'
import { NodeHttpHandler } from '@aws-sdk/node-http-handler'
import { exec } from 'child_process'
import { writeFile } from 'fs/promises'
import { Agent } from 'https'

const TEMP_CRONTAB_PATH = '/app/crontab.txt'
const WRAPPER_CMD = 'issp-ctl'

let isRegenerating = false

interface ScheduleJob {
	cron: string
}

interface Schedule {
	start?: ScheduleJob[]
	stop?: ScheduleJob[]
}

async function createCronJobs(
	instance: Instance,
	profileName: string,
	regionName: string,
) {
	const { InstanceId } = instance
	if (!InstanceId) return []

	// Simplified tag processing using the findTag utility
	const name = findTag('Name', instance, false)
	const displayName = name ? `${name} (${InstanceId})` : InstanceId

	const ownershipInfo = findTag('iv:self-service:ownership', instance)
	const notificationsChannel = ownershipInfo.notificationsChannel

	const schedule: Schedule = findTag('iv:self-service:schedule', instance)

	if (!schedule.start && !schedule.stop) {
		const rawScheduleValue = findTag(
			'iv:self-service:schedule',
			instance,
			false,
		)
		if (rawScheduleValue) {
			const errorMessage = `Invalid JSON in schedule tag for ${displayName}.`
			console.error(`${errorMessage} Value: "${rawScheduleValue}".`)
			await sendSlackNotification(
				`Found an invalid schedule for ${displayName}. It has been skipped.`,
				notificationsChannel,
			)
		}
		return []
	}

	const jobs: string[] = []
	const createJob = (cron: string, action: 'start' | 'stop'): string => {
		const cliCmd = `${WRAPPER_CMD} ${action} ${InstanceId} ${regionName} ${profileName}`
		return `${cron} ${cliCmd}`
	}

	schedule.start?.forEach((job) => jobs.push(createJob(job.cron, 'start')))
	schedule.stop?.forEach((job) => jobs.push(createJob(job.cron, 'stop')))

	return jobs
}

async function scanSchedules(profileName: string, regionName: string) {
	console.log(`Scanning Profile: ${profileName}, Region: ${regionName}`)

	const ec2Client = new EC2Client({
		region: regionName,
		profile: profileName,
		requestHandler: new NodeHttpHandler({
			httpsAgent: new Agent({ family: 4 }),
		}),
	})

	const command = new DescribeInstancesCommand({
		Filters: [{ Name: `tag-key`, Values: ['iv:self-service:schedule'] }],
	})

	const { Reservations = [] } = await ec2Client.send(command)
	const instances = Reservations.flatMap(
		(reservation) => reservation.Instances ?? [],
	)

	const jobPromises = instances.map((instance) =>
		createCronJobs(instance, profileName, regionName),
	)
	const jobsArray = await Promise.all(jobPromises)
	return jobsArray.flat()
}

async function fetchCronJobs() {
	const { profiles = {} } = await getConfig()
	console.log('Loaded profiles:', Object.keys(profiles).join(', ') || 'None')

	const scanTasks = Object.entries(profiles).flatMap(
		([profileName, profileDetails]) =>
			profileDetails.regions.map((regionName) =>
				scanSchedules(profileName, regionName),
			),
	)

	const results = await Promise.allSettled(scanTasks)
	const cronJobs: string[] = []

	for (const result of results) {
		if (result.status === 'fulfilled') {
			cronJobs.push(...result.value)
		} else {
			console.error('A region scan failed:', result.reason)
			await sendSlackNotification(
				`Failed to scan a region. Error: ${result.reason.message}`,
				undefined, // Global error, use default channel
			)
		}
	}
	return cronJobs
}

async function generateAndApplyCrontab() {
	try {
		isRegenerating = true
		console.log('Starting crontab generation.')

		const cronJobs = await fetchCronJobs()

		const crontabHeader = `# Auto-generated by ISSP on ${new Date().toISOString()}\n\n`
		const crontabContent = crontabHeader + cronJobs.join('\n') + '\n'

		await writeFile(TEMP_CRONTAB_PATH, crontabContent)
		console.log(`Wrote ${cronJobs.length} jobs to ${TEMP_CRONTAB_PATH}`)

		await exec(`crontab ${TEMP_CRONTAB_PATH}`)
		console.log('Cron schedule successfully installed.')
		await sendSlackNotification(
			`Instance schedules have been updated.`,
			undefined, // Global success, use default channel
		)
	} catch (error: any) {
		console.error('Error during crontab generation:', error)
		await sendSlackNotification(
			`Failed to update schedules. Error: ${error.message}`,
			undefined, // Global error, use default channel
		)
	} finally {
		isRegenerating = false
		console.log('Crontab generation process finished.')
	}
}

export async function triggerCronfileRegeneration() {
	if (isRegenerating) {
		console.log('Scheduler regeneration already in progress. Skipping.')
		return
	}
	console.log('Triggering background scheduler refresh.')

	generateAndApplyCrontab().catch((err) => {
		console.error('FATAL: Unhandled error in crontab generation.', err)
	})
}
